SET SERVEROUTPUT ON

CREATE OR REPLACE TYPE OBJ_COD_POSTAL AS OBJECT(
    LOCALIDAD NUMBER(3),
    PROVINCIA NUMBER(2)
);
/

CREATE OR REPLACE TYPE OBJ_DOMICILIO AS OBJECT(
    TIPO_VIA VARCHAR2(30),
    NOMBRE_VIA VARCHAR2(30),
    NUMERO NUMBER(3),
    RESTO_DOMICILIO VARCHAR2(50)
);
/

CREATE OR REPLACE TYPE OBJ_NOMBRE AS OBJECT(
    NOMBRE VARCHAR2(50),
    PR_APELLIDO VARCHAR2(50),
    SG_APELLIDO VARCHAR2(50)
);
/

CREATE OR REPLACE TYPE OBJ_DATOS_PERSONALES AS OBJECT(
    CODIGO_DP VARCHAR2(3),
    NOMBRE_COMPLETO OBJ_NOMBRE,
    DOMICILIO OBJ_DOMICILIO,
    CODIGO_POSTAL OBJ_COD_POSTAL,
    FECHA_NACIMIENTO DATE
);
/