SET SERVEROUTPUT ON

DECLARE
    NOMBRE_1 OBJ_NOMBRE := OBJ_NOMBRE('Ángela','Negro','Castilla');
    DOM_1 OBJ_DOMICILIO := OBJ_DOMICILIO('Avenida','Postigo',100,'1ºA');
    CP_1 OBJ_COD_POSTAL := OBJ_COD_POSTAL(001,41);
    DATOS_1 OBJ_DATOS_PERSONALES := OBJ_DATOS_PERSONALES('A5', NOMBRE_1, DOM_1, CP_1, '18/4/1991');
BEGIN
    DBMS_OUTPUT.PUT_LINE(DATOS_1.NOMBRE_COMPLETO.NOMBRE);
END;
/