SET SERVEROUTPUT ON

-- COD_POSTAL
-- Similar a DECLARE: Se define un procedimiento
-- No se puede utilizar 'create or replace' sobre el tipo anterior si hay un procedimiento porque sólo funciona con las variables. Hay que borrar la tabla anterior y ejecutar este 'create or replace' o darle un nombre distinto a esta
CREATE OR REPLACE TYPE OBJ_COD_POSTAL AS OBJECT(
    PROVINCIA NUMBER(3),
    LOCALIDAD NUMBER(2),
    MEMBER PROCEDURE INICIALIZAR_COD_POSTAL(P_PROVINCIA NUMBER, P_LOCALIDAD NUMBER)
);
/

-- Similar a BEGIN-END (o constructor): Se define lo que hace el procedimiento
CREATE OR REPLACE TYPE BODY OBJ_COD_POSTAL AS
    MEMBER PROCEDURE INICIALIZAR_COD_POSTAL(P_PROVINCIA NUMBER, P_LOCALIDAD NUMBER) IS
    BEGIN
        PROVINCIA := P_PROVINCIA; -- / SELF.PROVINCIA := PROVINCIA
        LOCALIDAD := P_LOCALIDAD;
    END INICIALIZAR_COD_POSTAL;
END;
/

--DOMICILIO
CREATE OR REPLACE TYPE OBJ_DOMICILIO AS OBJECT(
    TIPO_VIA VARCHAR2(30),
    NOMBRE_VIA VARCHAR2(30),
    NUMERO NUMBER(3),
    RESTO_DOMICILIO VARCHAR2(50),
    MEMBER PROCEDURE INICIALIZAR_DOMICILIO(P_TIPO_VIA VARCHAR2, P_NOMBRE_VIA VARCHAR2, P_NUMERO NUMBER, P_RESTO_DOMICILIO VARCHAR2)
);
/

CREATE OR REPLACE TYPE BODY OBJ_DOMICILIO AS
    MEMBER PROCEDURE INICIALIZAR_DOMICILIO(P_TIPO_VIA VARCHAR2, P_NOMBRE_VIA VARCHAR2, P_NUMERO NUMBER, P_RESTO_DOMICILIO VARCHAR2) IS
    BEGIN
        TIPO_VIA := P_TIPO_VIA;
        NOMBRE_VIA := P_NOMBRE_VIA;
        NUMERO := P_NUMERO;
        RESTO_DOMICILIO := P_RESTO_DOMICILIO;
    END;
END;
/

-- NOMBRE
CREATE OR REPLACE TYPE OBJ_NOMBRE AS OBJECT(
    NOMBRE VARCHAR2(50),
    PR_APELLIDO VARCHAR2(50),
    SG_APELLIDO VARCHAR2(50),
    MEMBER PROCEDURE INICIALIZAR_NOMBRE(P_NOMBRE VARCHAR2, P_PR_APELLIDO VARCHAR2, P_SG_APELLIDO VARCHAR2)
);
/

CREATE OR REPLACE TYPE BODY OBJ_NOMBRE AS
    MEMBER PROCEDURE INICIALIZAR_NOMBRE(P_NOMBRE VARCHAR2, P_PR_APELLIDO VARCHAR2, P_SG_APELLIDO VARCHAR2) IS
    BEGIN
        NOMBRE := P_NOMBRE;
        PR_APELLIDO := P_PR_APELLIDO;
        SG_APELLIDO := P_SG_APELLIDO;
    END;
END;
/

-- DATOS_PERSONALES
CREATE OR REPLACE TYPE OBJ_DATOS_PERSONALES AS OBJECT(
    CODIGO_DP VARCHAR2(3),
    NOMBRE_COMPLETO OBJ_NOMBRE,
    DOMICILIO OBJ_DOMICILIO,
    CODIGO_POSTAL OBJ_COD_POSTAL,
    FECHA_NACIMIENTO DATE,
    MEMBER PROCEDURE INICIALIZAR_DATOS_PERSONALES(P_CODIGO_DP VARCHAR2, P_NOMBRE_COMPLETO OBJ_NOMBRE, P_DOMICILIO OBJ_DOMICILIO, P_CODIGO_POSTAL OBJ_COD_POSTAL, P_FECHA_NACIMIENTO DATE)
);
/

CREATE OR REPLACE TYPE BODY OBJ_DATOS_PERSONALES AS
    MEMBER PROCEDURE INICIALIZAR_DATOS_PERSONALES(P_CODIGO_DP VARCHAR2, P_NOMBRE_COMPLETO OBJ_NOMBRE, P_DOMICILIO OBJ_DOMICILIO, P_CODIGO_POSTAL OBJ_COD_POSTAL, P_FECHA_NACIMIENTO DATE) IS
    BEGIN
        CODIGO_DP := P_CODIGO_DP;
        NOMBRE_COMPLETO := P_NOMBRE_COMPLETO;
        DOMICILIO := P_DOMICILIO;
        CODIGO_POSTAL := P_CODIGO_POSTAL;
        FECHA_NACIMIENTO := P_FECHA_NACIMIENTO;
    END;
END;
/

-- Probar objeto
DECLARE
    COD1 OBJ_COD_POSTAL := OBJ_COD_POSTAL(47,012);
BEGIN
    DBMS_OUTPUT.PUT_LINE(COD1.LOCALIDAD);
    COD1.INICIALIZAR_COD_POSTAL(37, 034);
    DBMS_OUTPUT.PUT_LINE(COD1.LOCALIDAD);
END;
/