SET SERVEROUTPUT ON

-- Crear el objeto y el tipo
CREATE OR REPLACE TYPE OBJ_PERSONA AS OBJECT(
    DNI VARCHAR2(9),
    NOMBRE VARCHAR2(50),
    PR_APELLIDO VARCHAR2(50),
    SG_APELLIDO VARCHAR2(50),
    FECHA_NACIMIENTO DATE,
    MEMBER FUNCTION MUESTRA_EDAD(FECHA_NACIMIENTO DATE) RETURN NUMBER
);
/

CREATE OR REPLACE TYPE BODY OBJ_PERSONA AS
    MEMBER FUNCTION MUESTRA_EDAD(FECHA_NACIMIENTO DATE) RETURN NUMBER IS
        EDAD NUMBER;
    BEGIN
        EDAD := TO_CHAR(SYSDATE,'yyyy') - TO_CHAR(FECHA_NACIMIENTO,'yyyy');
        RETURN EDAD;
    END;
END;
/

-- Probar objeto
DECLARE
    PERSONA OBJ_PERSONA := OBJ_PERSONA('49833472H','Jose','Fernández','Mena','10/01/2003');
BEGIN
    DBMS_OUTPUT.PUT_LINE(PERSONA.MUESTRA_EDAD(PERSONA.FECHA_NACIMIENTO));
END;
/