SET SERVEROUTPUT ON

-- Se debe ejecutar primero el 7.4
-- Bloque anónimo
DECLARE
    PERSONA OBJ_PERSONA := OBJ_PERSONA('74329872A','Pedro','García','Rodríguez','15/11/2000');
BEGIN
    DBMS_OUTPUT.PUT_LINE(PERSONA.NOMBRE);
    DBMS_OUTPUT.PUT_LINE(PERSONA.MUESTRA_EDAD(PERSONA.FECHA_NACIMIENTO));
END;
/