SET SERVEROUTPUT ON

-- Ejecutar primero 7.3
CREATE OR REPLACE TYPE OBJ_DATOS_PERSONALES AS OBJECT(
    CODIGO_DP VARCHAR2(3),
    NOMBRE_COMPLETO OBJ_NOMBRE,
    DOMICILIO OBJ_DOMICILIO,
    CODIGO_POSTAL OBJ_COD_POSTAL,
    FECHA_NACIMIENTO DATE
) NOT FINAL;
/

CREATE OR REPLACE TYPE OBJ_PROFESOR UNDER OBJ_DATOS_PERSONALES(
    FECHA_INCORPORACION DATE
);
/

CREATE OR REPLACE TYPE OBJ_ALUMNO UNDER OBJ_DATOS_PERSONALES(
    CALIF_EVAL_1 NUMBER,
    CALIF_EVAL_2 NUMBER,
    CALIF_EVAL_3 NUMBER,
    CALIF_EVAL_4 NUMBER
);
/

-- Bloque anónimo
DECLARE
    PROFESOR OBJ_PROFESOR;
    ALUMNO OBJ_ALUMNO;
    
    -- PROFESOR
    NOMBRE_1 OBJ_NOMBRE := OBJ_NOMBRE('Ángela','Negro','Castilla');
    DOM_1 OBJ_DOMICILIO := OBJ_DOMICILIO('Avenida','Postigo',100,'1ºA');
    CP_1 OBJ_COD_POSTAL := OBJ_COD_POSTAL(001,41);
    -- ALUMNO
    NOMBRE_2 OBJ_NOMBRE := OBJ_NOMBRE('Pedro','García','Rodríguez');
    DOM_2 OBJ_DOMICILIO := OBJ_DOMICILIO('Avenida','Postigo',305,'2ºB');
    CP_2 OBJ_COD_POSTAL := OBJ_COD_POSTAL(200,52);
BEGIN
    PROFESOR := NEW OBJ_PROFESOR('172', NOMBRE_1, DOM_1, CP_1, '05/06/2000', '05/06/2020');
    ALUMNO := NEW OBJ_ALUMNO('749', NOMBRE_2, DOM_2, CP_2, '03/02/2010', 5, 4, 7, 6);
    
    -- Mostrar datos de ejemplo
    DBMS_OUTPUT.PUT_LINE(PROFESOR.DOMICILIO.RESTO_DOMICILIO);
    DBMS_OUTPUT.PUT_LINE(ALUMNO.DOMICILIO.RESTO_DOMICILIO);
END;
/