SET SERVEROUTPUT ON

CREATE OR REPLACE TYPE OBJ_EMPLEADO AS OBJECT(
    DNI VARCHAR2(9),
    NOMBRE VARCHAR2(30),
    AP1 VARCHAR2(30),
    AP2 VARCHAR2(30),
    TELEFONO VARCHAR2(9)
) NOT FINAL;
/

-- Crear tipos inspector y policía que heredan de empleado
CREATE OR REPLACE TYPE OBJ_INSPECTOR UNDER OBJ_EMPLEADO(
    ESPECIALIDAD VARCHAR2(30)
);
/

CREATE OR REPLACE TYPE OBJ_POLICIA UNDER OBJ_EMPLEADO(
    CATEGORIA VARCHAR2(30),
    SALARIO_BASE NUMBER,
    MEMBER FUNCTION CALCULAR_SALARIO(SALARIO_BASE NUMBER) RETURN NUMBER
);
/

-- Función calcular_salario de policía
CREATE OR REPLACE TYPE BODY OBJ_POLICIA AS
MEMBER FUNCTION CALCULAR_SALARIO(SALARIO_BASE NUMBER) RETURN NUMBER IS
    V_SALARIO_BASE NUMBER := SALARIO_BASE;
    V_SALARIO NUMBER := 0;
    BEGIN
        IF SELF.CATEGORIA = 'LOCAL' THEN
            V_SALARIO := V_SALARIO_BASE * 1.05;
        ELSIF SELF.CATEGORIA = 'NACIONAL' THEN
            V_SALARIO := V_SALARIO_BASE * 1.15;
        ELSIF SELF.CATEGORIA = 'OPERACIONES ESPECIALES' THEN
            V_SALARIO := V_SALARIO_BASE * 1.2;
        END IF;
        
        RETURN V_SALARIO;
    END;
END;
/

-- Crear tablas
CREATE TABLE POLICIAS OF OBJ_POLICIA;
CREATE TABLE INSPECTORES OF OBJ_INSPECTOR;